
export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';


export const ADD_PRODUCT = 'ADD_PRODUCT';


export const PAY_PRODUCT_REQUEST = 'PAY_PRODUCT_REQUEST';
export const PAY_PRODUCT_SUCCESS = 'PAY_PRODUCT_SUCCESS';
export const PAY_PRODUCT_FAILURE = 'PAY_PRODUCT_FAILURE';
